// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edvdbckamxlfhrntcmeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdmRiY2thbXhsZmhybnRjbWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDIyMDAsImV4cCI6MjA3NDIxODIwMH0.zHmiN8O0uKKadWcAaYUJ4oA8zT0MM5_QLbheXNwB67E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});